feat: add more data and fix minor issues
dasch-swiss/dsp-meta-svc pull request #26
Opened 2022-01-11 10:52 UTC by BalduinLandolt

resolves DEV-355

2022-01-25 08:23 UTC, mpro7 requested changes
Look good, but I have problem with opening below projects: http://localhost:3000/projects/083B
![image](https://user-images.githubusercontent.com/29251288/150937760-ceb1ccbd-1897-456d-a565-d00bcd800e58.png)

2022-01-25 09:53 UTC, mpro7 commented
IMO above error is because person `http://ns.dasch.swiss/repository#dsp-083B-person-002` doesn't have a `jobTitle` which is required

2022-01-31 10:07 UTC, BalduinLandolt commented
@danielasubotic the issue reported by @mpro7 was actually an old build artifact messing things up, in an up to date build, this doesn't happen. I added a build task to the make target he used, so this can't happen again. I think, this should then be good to merge

2022-01-31 10:33 UTC, mpro7 approved these changes

2022-01-31 12:13 UTC, merged